### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bartfeenstra** [KotlinIsland/basedtyping#113]
Hi there! Could you please add a license to the project? I noticed basedmypy is MIT but that's probably primarily because it's a fork. I couldn't find any license information on the basedtyping project.

**Comment by KotlinIsland** [comment]
Mit?

**Comment by bartfeenstra** [comment]
Is that you questioning me mentioning the MIT, or you suggesting basedtyping is/may be released under the MIT?  :)

**Comment by KotlinIsland** [comment]
Haha, sorry. Do you think MIT would make sense?

**Comment by bartfeenstra** [comment]
Under the condition it's allowed (I don't know the history of the basedtyping codebase) then yes, the MIT is a great license for interoperability and compatibility with other free software licenses.

**Comment by bartfeenstra** [comment]
When I say "allowed", that means by the authors. Assuming none of the repo code was copied from elsewhere, that appears to be you and @DetachHead

**Comment by KotlinIsland** [comment]
https://github.com/KotlinIsland/basedtyping/commit/404b7df1852c90e55d955f5a450b2d86851535a7

Do you need me to release it?

**Comment by bartfeenstra** [comment]
Excellent! A release is not a hard requirement for me at this time. I can wait until the next one naturally comes around.

Thanks!
