### ISSUE TITLE
why doesn't `deprecated` have a `condition`/`when` flag?

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedtyping#137]
why doesn't `deprecated` have a `condition`/`when` flag?
```py
@deprecated("asdf", when=sys.version_info >= (3, 12))
def f(): ...
```

_Originally posted by @KotlinIsland in https://github.com/KotlinIsland/basedtyping/issues/128#issuecomment-2315129471_

**Comment by jorenham** [comment]
dupe of #130

**Comment by KotlinIsland** [comment]
fail
