### ISSUE TITLE
`cast` should perform a static check to ensure type overlap

### ISSUE THREAD

**Issue by DetachHead** [KotlinIsland/basedtyping#25]
https://github.com/python/mypy/issues/11958

relates #3

**Comment by KotlinIsland** [comment]
Isn't this a basedmypy issue? Or are you suggesting a `based_cast` method in `basedtyping`.

**Comment by DetachHead** [comment]
a `based_cast` method if it can be implemented within the language. if not then we'll transfer the issue to basedmypy

**Comment by KotlinIsland** [comment]
imo upgrade `cast` to work properly, and add a runtime checking cast.

**Comment by KotlinIsland** [comment]
Resolved in basedmypy, no idea how to type cast as is.
