### ISSUE TITLE
`T_in` and `T_out` `TypeVar`s 

### ISSUE THREAD

**Issue by KotlinIsland** [KotlinIsland/basedtyping#61]
`in` / `out` is based

**Comment by DetachHead** [comment]
we already have `T_co` and `T_cont`

**Comment by KotlinIsland** [comment]
But `in` / `out` is based

**Comment by DetachHead** [comment]
so just rename them?

**Comment by KotlinIsland** [comment]
Hmmm, if they are the same thing, and more based, then yes?
